### PR TITLE
Upgrade to ppxlib 0.18.0

### PR DESCRIPTION
**Pull request by kit-ty-kate**
The opam file was missing from the repository which prevented accurate opam pinning

### CODE REVIEW

**Comment by kit-ty-kate** [comment]
It looks like I misinterpreted the failure. It's fixed now.

**Comment by kit-ty-kate** [comment]
fixes https://github.com/thierry-martinez/metapp/issues/1

**Comment by kit-ty-kate** [comment]
~`stdcompat` seems to somehow be tied to the version of ppxlib via its `interface_dumper` generated module. I'm a bit confused.~

Edit: nevermind

**Comment by thierry-martinez** [comment]
Thank you very much, @kit-ty-kate , for this upgrade! Merged.

I am a bit perplex about versioning the opam file: I deliberately chose not to version it, since it is auto-generated, but I know that it makes opam pinning harder. I don't know what is the right thing to do...

**Pull request merged**
